### ISSUE TITLE
Wrong sorting

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/client#918] opened 2017-12-17 22:02 UTC
![image](https://user-images.githubusercontent.com/19996713/34084318-4093b062-e37e-11e7-9abe-24f760a4eac1.png)
I updated and after this games are not sorted by players anymore!

**Comment by Wesmania** [comment] 2017-12-17 22:11
I can't seem to reproduce it. Did you try switching the sort option to something else and back?

**Comment by 1-alex98** [comment] 2017-12-17 22:18
Yeah then it orders correctly

**Comment by 1-alex98** [comment] 2017-12-17 22:18
But when I restart, the problem is back there

**Comment by Wesmania** [comment] 2017-12-17 22:26
Okay, I can reproduce it. Must be some issue with properly updating sort order. I'll look into it.

**Comment by 1-alex98** [comment] 2017-12-17 22:34
Cool!

**Comment by Wesmania** [comment] 2017-12-17 22:51
Alright, I located the problem. I thought the combo box would notify the code when its index was initialized, but it turns out it only does that when the index actually changes - and the default index is exactly the sorting by players. Fix is prepared, will be merged and end up in the next RC. Thanks for the report!

**Comment by Wesmania** [comment] 2017-12-17 23:01
Submitted and merged (and I forgot about the magical 'Fixes #918' line that would auto-close it, of course). Thanks again!

**Closed as completed by Wesmania** 2017-12-17 23:01 UTC

**Comment by 1-alex98** [comment] 2017-12-18 16:54
Is a pleasure for me :D If only more people would create issues for the java client ;)
