### ISSUE TITLE
Old steam link prompted upon login

### ISSUE THREAD

**Issue by Viba** [FAForever/client#902] opened 2017-12-06 17:08 UTC
Old steam link prompted upon login, returns 503 page.
https://gyazo.com/3ade59e991ba597783456d351235138d

Should be: https://www.faforever.com/account/link

**Comment by ghost** [comment] 2017-12-06 17:27
Wrong repo. It is server side, we only show what the server told us for this case : 
https://github.com/FAForever/server/blob/develop/server/lobbyconnection.py#L568 

Oh I think I may have already made a PR a while ago about it : 
https://github.com/FAForever/server/pull/318

So if someone else can confirm, to close this issue.

**Comment by Wesmania** [comment] 2017-12-06 17:31
I can't reproduce this either, and for all I can tell this is exactly the URL that's used (it gets redirected to another address, so maybe that's the source of confusion). I'll close this.

**Closed as completed by Wesmania** 2017-12-06 17:31 UTC
