### ISSUE TITLE
Medicraze again...it happend

### ISSUE THREAD

**Issue by Medicraze** [FAForever/client#367] opened 2016-06-14 03:29 UTC
[uid.txt](https://github.com/FAForever/client/files/313079/uid.txt)
[forever.txt](https://github.com/FAForever/client/files/313078/forever.txt)

error is occuring while joining a ladder match...loading launches, and then i get an error that is automatically sent or something...it's weird...

deering took a look at my last one and said something about a porting error...

**Comment by ChrisKitching** [comment] 2016-06-23 21:39
Duplicate of #366

**Comment by ChrisKitching** [comment] 2016-06-23 21:40
Duplicate of #366

**Closed as completed by ChrisKitching** 2016-06-23 21:39 UTC
Labels: duplicate
