### ISSUE TITLE
Stop games moving around on the Play tab

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/client#685] opened 2017-03-25 21:05 UTC
It's very annoying to click on the wrong game because they keep moving.

**Comment by GrotheFAF** [comment] 2017-03-27 20:37
You know that this caused by the sorting (by changing player count), right?
What would you want, no sorting?

**Comment by Wesmania** [comment] 2017-03-27 20:49
We could perhaps disable / reenable the sorting on mouseover events. Then again, we'd have to figure out what to do about games added to / removed from the list.

**Comment by GrotheFAF** [comment] 2017-03-28 00:43
The halt sorting seems hard to do, (dis- and reenabling sorting would change games to unsorted and back to sorted, not what you want), but we could add sorting options for the hosted games by not or less changing things like: [game]uid: new hosted games would add at the end. (and leaving games would drop ot of list) or host name, max players, map name. (it still would have friends on top)

**Comment by duk3luk3** [comment] 2017-03-28 05:54
I know I've already been in a discussion about this. So there's probably already an issue.

There are several options we have:

1. Completely disable auto-refresh; only refresh when user switches to the tab or clicks an explicity refresh button
2. Freeze state of grid when user mouses into grid view, update otherwise - this might not be very intuitive
3. Freeze state of grid when user switches to tab - deleted / launched games get a visual indicator (e.g. "grayed out"), new games are only added to the end

I will merge whatever works (and uses maintainable code).

**Comment by GrotheFAF** [comment] 2017-03-28 15:05
How would you actually do 1.-3.? The GameItems in GamesWidget are updated from server messages, so you don't want to hold/freeze that, if you freeze the display of the widget, what GameItem would you actually click?
Another question is why the GameWidget has to hold all the hidden(state='playing') games, aside from keeping the urls uptodate.

**Comment by muellni** [comment] 2017-04-06 14:23
possible duplicate of #567

**Comment by chris400** [comment] 2017-04-17 00:37
my suggestion: don't join by doubleclick, join by selecting a game and then have a button _join_

**Comment by duk3luk3** [comment] 2017-04-18 06:27
That's a good idea. Selecting a game could freeze the view until it is deselected / a "Refresh" button is clicked (or the tab is changed).

**Comment by chris400** [comment] 2017-04-18 07:07
If you only can join by clicking a button, there is no need to freeze the view IMHO

**Comment by Wesmania** [comment] 2018-01-01 19:30
Duplicate of #567.

**Closed as completed by Wesmania** 2018-01-01 19:30 UTC
