### ISSUE TITLE
Yet another rating bug

### ISSUE THREAD

**Issue by JonnoHR31** [FAForever/client#1029] opened 2018-05-14 07:00 UTC
**I experienced...** Won a game, no change in rank, replay vault shows both teams lost and has a -1 next to all players. No desync message appeared in game and nothing happened that would typically cause a desync. 

Replay 7929079

[7929079-SaltyHeart.zip](https://github.com/FAForever/client/files/1999622/7929079-SaltyHeart.zip)

**how to reproduce** Completely random, some games end up unranked for no obvious reason, seems to happen in particular with long games that experience people rage quitting (not exiting correctly and having to be ejected). 

**I expected...** The game to be ranked.

**Where the bug is / What should be done** No idea, not the first time this bug has happened so I'm sure someone will know all about it :).

**Comment by Sheeo** [comment] 2018-05-14 07:51
Not a bug. The map you played has been marked as unranked.

You should talk with the mapping councilor if this is a mistake.

**Closed as completed by Sheeo** 2018-05-14 07:51 UTC

**Comment by JonnoHR31** [comment] 2018-05-14 12:27
Previous games on this exact map version have been ranked? Has this recently (in the last 2 months) been made unranked? 

This also doesn't explain why the replay vault shows this game as both teams losing and a -1 for all players, even unranked maps still show the winning team and who was left alive on that team.

**Comment by Wesmania** [comment] 2018-05-14 14:59
Neither the rating or the vault data issues are client issues - they're server issues. Please report them at https://github.com/FAForever/server instead.
