### ISSUE TITLE
Medicraze again...it happened once again

### ISSUE THREAD

**Issue by Medicraze** [FAForever/client#374] opened 2016-06-17 03:12 UTC
same shit... :(
[forever.txt](https://github.com/FAForever/client/files/319702/forever.txt)
[uid.txt](https://github.com/FAForever/client/files/319703/uid.txt)

**Comment by ChrisKitching** [comment] 2016-06-23 21:39
Duplicate of #366

**Closed as completed by ChrisKitching** 2016-06-23 21:39 UTC
Labels: duplicate
