### ISSUE TITLE
Medicraze Ladder launch issues

### ISSUE THREAD

**Issue by Medicraze** [FAForever/client#366] opened 2016-06-13 21:32 UTC
[forever.txt](https://github.com/FAForever/client/files/312753/forever.txt)
[uid.txt](https://github.com/FAForever/client/files/312754/uid.txt)

here you go. Thanks for the hard work guys.

**Comment by HardlySoftly** [comment] 2016-06-21 21:24
Definitely something weird here, we seem to be reaching this line of code: https://github.com/FAForever/client/blob/develop/src/fa/game_session.py#L130 with self._game_connection still being 'None'.

Is it possible that the server is sending out connection messages in the wrong order sometimes, meaning that the new connection setup is reaching the client after it gets this _peer_bound message?

This would explain why the problem isn't specific to one person

**Comment by HardlySoftly** [comment] 2016-06-21 21:25
Also worth closing https://github.com/FAForever/client/issues/374 and https://github.com/FAForever/client/issues/367 as duplicates of this issue.

**Comment by micheljung** [comment] 2016-06-25 07:07
Duplicate of #359 (See my comment there)

**Comment by micheljung** [comment] 2016-09-10 12:36
Analyzed and fixed in #359

**Closed as completed by micheljung** 2016-09-10 12:36 UTC
Labels: duplicate
