### ISSUE TITLE
[develop] Unable to Host a game

### ISSUE THREAD

**Issue by Frozen-byte** [FAForever/client#178] opened 2015-02-19 16:33 UTC
I am not able to host a game, because something is wrong with the version. When clicking on "Host Game" button the following exception is thrown
```
2015-02-19 17:30:11,340 ERROR    __main__                       Uncaught exception                                                                           
Traceback (most recent call last):                                                                                                                           
  File "src/games/_gameswidget.py", line 665, in hostGameClicked                                                                                             
    version = hostgamewidget.selected_game_version                                                                                                           
  File "src/games/hostgamewidget.py", line 147, in selected_game_version                                                                                     
    version = self.versions[self.selectedVersion]                                                                                                            
IndexError: list index out of range                                                                                                                          
```

I have checked the variables, they are all unset, zero or empty.

Version: FAF development version: '0.11-pre-3-27-g970fba6'

**Comment by IDragonfire** [comment] 2015-04-03 12:15
confirmed

**Comment by IDragonfire** [comment] 2015-04-03 12:29
https://github.com/FAForever/client/blob/develop/src/games/hostgamewidget.py#L81

versions array is always empty ...
I find no method that call `set_versions`
https://github.com/FAForever/client/blob/develop/src/games/hostgamewidget.py#L128

Even more strange
If you double click on "Creage Custom Game"
`selected_game_version` is called,
but no `self.versions` object exists.
https://github.com/FAForever/client/blob/develop/src/games/hostgamewidget.py#L142

Reason:
https://github.com/FAForever/client/blob/develop/src/games/hostgamewidget.py#L54

setupUi calls the `selected_game_version` before `self.versions` is initialized.
But why?
Because it is marked as an `property?

![image](https://cloud.githubusercontent.com/assets/1217999/6982141/784ec80c-da0d-11e4-89f9-fb5af09defac.png)

**Comment by Sheeo** [comment] 2015-04-03 14:25
Right, this relies on the version api exposed by the dserver, which is currently not running on dev, so it doesn't get an expected response, resulting in this.

**Closed** 2015-08-24 19:52 UTC
