### ISSUE TITLE
Help with Forged Alliance Forever

### ISSUE THREAD

**Issue by grabby512** [FAForever/client#285] opened 2016-01-23 17:51 UTC
**FAF Username:** PIMPS420

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** D:\Users\Matthew\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "replays\_replayswidget.pyc", line 121, in finishRequest
  File "fa\exe.pyc", line 150, in replay
  File "json\__init__.pyc", line 338, in loads
  File "json\decoder.pyc", line 365, in decode
  File "json\decoder.pyc", line 383, in raw_decode
ValueError: No JSON object could be decoded

}}}

**Comment by yorick-ne** [comment] 2016-01-24 17:11
looks like it is the same issue as #270, which seems to be fixed in the beta client

**Comment by Sheeo** [comment] 2016-01-29 13:45
Indeed a duplicate of #270, closing.

**Closed by Sheeo** 2016-01-29 13:45 UTC
