### ISSUE TITLE
Crash on opening replay in vault

### ISSUE THREAD

**Issue by GuyGuyGuy** [FAForever/client#184] opened 2015-03-11 18:26 UTC
Any more info needed PM me.

**FAF Username:** Guy
**FAF Version:** 0.10.122
**FAF Directory:** C:\ProgramData\FAForever
**FA Path:** D:\Steam Library\SteamApps\common\Supreme Commander Forged Alliance
**Home Directory:** C:\Users\G\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "replays\_replayswidget.pyc", line 121, in finishRequest
  File "fa\exe.pyc", line 150, in replay
  File "json\__init__.pyc", line 338, in loads
  File "json\decoder.pyc", line 366, in decode
  File "json\decoder.pyc", line 384, in raw_decode
ValueError: No JSON object could be decoded

}}}

**Comment by GuyGuyGuy** [comment] 2015-03-11 18:28
Sorry, just noticed this is similar to #179

**Comment by Sheeo** [comment] 2015-03-11 18:45
Indeed a duplicate of #179, thanks for the report though :)

**Closed by Sheeo** 2015-03-11 18:45 UTC
