### ISSUE TITLE
Some user in chat userlist are shown in zombie games

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/client#704] opened 2017-04-22 00:28 UTC
Some users in chat are shown 'in game' (crossed sword), but the games are actually older zombie games of these users.
A workaround (until this is fixed server side) would be, not to process/ignore the zombie games (>12 hours) when getting the games from server on client startup.

**Comment by Wesmania** [comment] 2017-04-22 10:07
We've talked a while about it already, I think? We even located the cause of the bug on the server, and fixing it there would be the right thing to do. It'd be easier to deploy the fix on the server rather than fix it with a client release that will have to be reverted once the bug is fixed.

I know that the fix won't make it to the server before ICE, since it touches the server code quite a bit, but we'll have to deal with it just a while longer.

**Comment by duk3luk3** [comment] 2017-04-25 04:45
Hiding games that are more than 12 hours old is still a good idea. And I don't see why we'd have to revert that.

**Comment by Wesmania** [comment] 2017-04-25 10:46
I don't think so, certainly not without giving players a toggle option for that. That wouldn't be a problem anyway if the server didn't have the zombie game bug, I suggest we fix that instead.

**Comment by GrotheFAF** [comment] 2017-04-25 11:08
Currently the server issue is there, and it has effect in the client, a temp fix is better than no fix.
Come back, when you fixed that server issue. ('we fix' doesn't do anything.)
(and toggle option? really: like an option for: yes/no: want shit on my shoes ;-)

**Comment by GrotheFAF** [comment] 2017-04-28 00:19
a snapshot of the difference:
![fafclient-chat-user-with out -zombie](https://cloud.githubusercontent.com/assets/19195504/25509462/7c3b66f0-2bb9-11e7-921c-4451680107c0.jpg)

**Comment by GrotheFAF** [comment] 2017-05-17 01:37
Are 'we' happy with the current server solution? Is it working as expected?
So that I can close this?

**Comment by Wesmania** [comment] 2017-05-17 19:21
I believe that the server issue is partially fixed- we definitely no longer lose games forever. I've noticed that there's still another kind of issue - some games stay open as long as a player that played them stays online. Whether this is caused by a bug is left to investigate. It might be just players that don't close their FA, or we might be losing the 'FA closed' message from the client in one way or another.

In the first case I think the smart way to fix it would be to tell the client about individual players leaving the game - correct me if I'm wrong, but I think right now we determine whether the player is playing the game using the game state messages, so players that left a game early are marked as 'playing' until the server decides the game ended. It'd be a significant change since it involves changing server protocol, but it should be possible to add it while keeping backwards compatibility.

Anyway, for all I can tell there are significantly less 'zombie' games now, and culling them doesn't make much of a difference. You can try and make another comparison with and without the client fix.

**Comment by GrotheFAF** [comment] 2017-05-17 21:07
In my debug 'Live Games' I see all server games (unfiltered), and since server update all games I've seen are less than a day old. That is good.

To the second point: you're right - afaik. 
Aside from being shown still ingame, this is might be problematic if someone left a still runing game and joins another.
The server seems to send game updates while game is in state playing, not sure (yet) what the update should update ... as far as I have checked, I didn't see any player changes.... under investigation.

**Comment by Wesmania** [comment] 2017-05-21 09:39
I think we can close this, since the zombie game bug is fixed.

**Closed as completed by Wesmania** 2017-05-21 09:39 UTC

**Comment by GrotheFAF** [comment] 2017-05-21 09:55
It would a good idea to add a reverence to the (actual) fix. (so we don't wonder if it was magic ;-)
And we should revert #705. -> done #733

**Comment by GrotheFAF** [comment] 2017-05-21 10:49
... and I see currently one older game from the 19th #6229163, bummer.

**Comment by Wesmania** [comment] 2017-05-21 10:51
One of the players that played it is still online, so it's not a zombie - it'll disappear once the player logs out / plays another game. We'll have to figure out why it happens for sure, though it isn't as pressing.

**Comment by GrotheFAF** [comment] 2017-05-21 11:09
ok, so that is the fix (on server).
