### ISSUE TITLE
Get a bug report after 2nd+ click on ladder 'Play!' (branch/develop)

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/client#679] opened 2017-03-23 03:22 UTC
since last rebase (+connection.py):
Start client - Click 'Play!' - Click 'Stop search' - Click 'Play!' - BugMsg
Hosting and joining games works most of the time, but sometimes hangs in 'connecting..' and gives a BugMsg on next try.
I noticed from time to time waits for server read from a second up to 12 seconds.

the forever.log includes may tries with search, hosting and joining.
[forever.log.txt](https://github.com/FAForever/client/files/863465/forever.log.txt)

_To be clear, the following is happening for a long time, so not part of the above new thing:_
My first ladder game nearly always results in a bug report during FA 'connecting...'. After canceling FA, the next games work fine. (aside from the server stops talking to 'me' (updating Games) on a lot of days .. with constant refafs .. old story ... which 'feels' that it got better, but no good data on that)
(I just now needed 3 refaf until the server kept updating Play.. and first ladder worked (without bugmsg), go figure...)

**Comment by Wesmania** [comment] 2017-03-23 16:59
I'm able to reproduce that same exception before the commits that added connection.py. It's most likely an unrelated bug, I don't even know if it's a regression or if it just slipped by for so long. We can maybe check if the same bug can be made to happen in 0.12.2.

**Comment by Wesmania** [comment] 2017-03-23 17:05
I can also reproduce that on 0.12.4, don't think we can go back any further. It also seems to be some race condition, it takes a couple tries to trigger and usually when you start / stop searching very fast.

**Comment by GrotheFAF** [comment] 2017-03-23 18:03
I just had another variation (12.4 installed version, no IDE):
start Client - Play tab no updates* - click 'Play!' - click 'Stop..' - Click 'Play!' suddenly masive update activity in hosted games list and BugMsg - click 'Stop..' (and Play tab went silent again (maybe after a few seconds), more 'Play!'/'Stop..' didn't bring up the Bug again.
Another variation is: click 'Play!' and get an FA start that is stuck in 'Setting up ...', next refaf I got a game on first 'Play!' (and lost of course)  (not in .log)
So not really reproducable.
[faforever.log.txt](https://github.com/FAForever/client/files/865614/faforever.log.txt)

* chat and online replays is still working, but Live Games not updating. Does anyone has that too?

**Comment by Wesmania** [comment] 2017-03-23 18:33
That's weird, I could reproduce the exact same exception. I think we can agree that the code in the "fa" folder is a race condition ridden mess that we'll need to tackle eventually. I have no idea for how long it behaved like this anyway.

**Comment by GrotheFAF** [comment] 2017-03-29 01:05
Another thing/bug: Blackheart told me: to be able to watch his recent replays I have to dl his mod, 'just write 'august' into mod and enter', while that shows his mod 'Pre_August...' (+ a 2nd mod) in 0.12.4, **nothing**  shows up in the develop version.
I installed that mod in 0.12.4. and it shows up in green (= installed).
It does not show in develop (even though Blackhearts replays now run without desync, so it's installed, but a 'no show')
still working here: ce18e3796aa70fbe44842d631604064636e23507 - Modify _clientwindow and related classes to use lobby connection
stopped working from here: 137b05f6ee20786c560f4704190cd8325bd56112 - Move trivial message handlers to connection class
(should I make a new issue for this?)

**Comment by Wesmania** [comment] 2017-03-29 10:52
This is probably because of #683, #684 fixes that and should be merged very soon.

**Comment by GrotheFAF** [comment] 2017-03-29 14:17
Yes, tested it, fixes the above mod bug (in develop).
(but not  the 'Play!' bug.)

**Closed as completed** 2017-04-09 08:44 UTC
