### ISSUE TITLE
Reenable and rename the "choose maps" button.

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/client#290] opened 2016-02-05 20:12 UTC
Like the title says, renaming the button to "show the current rotation" and doing that would be great.
Also possibly a notification if you start searching for the first time after the rotation changed e.g "the rotation changed since you played last, do you want to view it or keep searching y/n"

**Comment by yorick-ne** [comment] 2016-08-29 11:00
I can have a go at this.
What is the intended behaviour here ? Some button either in the play tab next to all the ladder stuff or somewhere in the mapvault that opens a new window showing the maps ? I could also imagine having this as a seperate tab in the vault, but that would possibly make the ui less user friendly.

**Comment by Crotalus** [comment] 2016-08-29 11:30
I would vote for a button / icon near the ladder stuff in Play which shows a dialog or panel with the maps.

**Comment by Wesmania** [comment] 2018-01-01 18:30
"Retroactive" duplicate of #889.

**Closed by Wesmania** 2018-01-01 18:30 UTC
Labels: ready, usability
