### ISSUE TITLE
Tutorials Tab Broken

### ISSUE THREAD

**Issue by thygrrr** [FAForever/client#532] opened 2016-12-18 19:22 UTC
**I experienced...** 

Clicking on any of the Hyperlinks in the Tutorials Tab results in a 404 HTTP error page being shown.

**I expected...** 

Nice tutorial pages should show up... or (maybe better), the ugly Tutorial Tab is just removed from FAF (it's probably hardcoded)

**Where the bug is / What should be done** 

Remove FAF Tutorials tab. Even if content could still be found, it's likely not up to date anymore with all the engymod stuff.

Alternatively, restore the pages. However, I find the tutorials tab is somewhat poorly implemented (just a rich text view)

**Comment by duk3luk3** [comment] 2016-12-18 20:26
Thanks! Probably a side effect of the website migration. Will see what we'll do about it.

**Comment by JaggedAppliance** [comment] 2016-12-18 20:27
I'm pretty sure the broken links were fixed months ago. 
edit: #389

**Comment by duk3luk3** [comment] 2016-12-18 20:30
Well I can't reproduce your specific issue on current develop (aka 0.12.0 preview).

But there also aren't any tutorials. (This might just be my VM that doesn't even have supcom installed)

**Comment by Exotic-Retard** [comment] 2016-12-18 20:53
related issue: https://github.com/FAForever/client/issues/18
(the irony)
also lovely to see you here thygrrr

**Comment by thygrrr** [comment] 2016-12-18 22:46
@duk3luk3  I can confirm this bug doesn't occur in Preview 0.12.x

Still making a case to redesign this tab. :)

**Comment by duk3luk3** [comment] 2016-12-19 05:46
PRs welcome :)

**Comment by ghost** [comment] 2017-11-13 03:02
Seems like it is fixed now, I don't have any issue in showing the tutorial tab.

If it is about the content, then another issue should be made or this one should be renamed I guess..?

**Comment by Wesmania** [comment] 2018-01-01 19:16
Closing.

**Closed as completed by Wesmania** 2018-01-01 19:16 UTC
