### ISSUE TITLE
FAF:Crash from starting CO-OP

### ISSUE THREAD

**Issue by RockyTurtle** [FAForever/client#228] opened 2015-08-21 14:22 UTC
I have cleared my game cache multiple times yet still get the exact same issue:

**FAF Username:** Godfather

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Games\Steam\steamapps\common\Supreme Commander Forged Alliance

**Home Directory:** C:\Users\Simon\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\ProgramData\\FAForever\\cache\\patchedFile'

}}}

**Comment by Sheeo** [comment] 2015-08-21 14:44
Duplicate of https://github.com/FAForever/client/issues/225

**Closed by Sheeo** 2015-08-21 14:44 UTC
Labels: duplicate
